#!/bin/sh
#########################################################################################################

#check ebin directory
if [ ! -d ebin ]; then
	echo "ERROR: beam directory is not!"
	exit 1
fi

#get server host name
HostName=`hostname`
ECHO="echo -e"
CtlNode_ProcessNum=4194304
CtlNode_PortNum=2048
ConnNode_ProcessNum=1572864
ConnNode_PortNum=1048576
PushNode_ProcessNum=4096
PushNode_PortNum=2048


#import functions
. ./functions

#cd beam directory
cd ebin

if [ $# -gt 0 ]; then
	restart_type="$1"
else
	restart_type="all"
fi

if [ $restart_type = "all" -o $restart_type = "push" ]; then 
	restart_push_nodes $PushNode_ProcessNum $PushNode_PortNum

if [ $restart_type = "all" -o $restart_type = "conn" ]; then 
	restart_conn_nodes $ConnNode_ProcessNum $ConnNode_PortNum
fi

if [ $restart_type = "all" -o $restart_type = "ctl" ]; then
	restart_ctl_nodes  $CtlNode_ProcessNum $CtlNode_PortNum
fi

if [ $restart_type = "ctlnode" ]; then
	restart_ctl_node $2 $CtlNode_ProcessNum $CtlNode_PortNum
fi

if [ $restart_type = "backctlnode" ]; then
	restart_backup_ctl_node $2 $CtlNode_ProcessNum $CtlNode_PortNum
fi

if [ $restart_type = "connnode" ]; then
	restart_conn_node $2 $ConnNode_ProcessNum $ConnNode_PortNum
fi

if [ $restart_type = "pushnode" ]; then
	restart_push_node $2 $PushNode_ProcessNum $PushNode_PortNum
fi


unset HostName
unset restart_type
unset ECHO
unset CtlNode_ProcessNum
unset CtlNode_PortNum
unset ConnNode_ProcessNum
unset ConnNode_PortNum
unset PushNode_ProcessNum
unset PushNode_PortNum

