#!/bin/sh
#########################################################################################################

#check ebin directory
if [ ! -d ebin ]; then
	echo "ERROR: beam directory is not!"
	exit 1
fi

HostName=`hostname -f`
ECHO="echo -e"
CtlNode_ProcessNum=4194304
CtlNode_PortNum=2048
ConnNode_ProcessNum=1572864
ConnNode_PortNum=1048576
PushNode_ProcessNum=4096
PushNode_PortNum=2048



#import functions
. ./functions

#cd beam directory
cd ebin

# start control and backup control nodes, see "./functions"
start_ctl_nodes $CtlNode_ProcessNum $CtlNode_PortNum

#start mobile connection nodes, see "./functions"
start_conn_nodes $ConnNode_ProcessNum $ConnNode_PortNum

#start server push nodes, see "./functions"
start_push_nodes $PushNode_ProcessNum $PushNode_PortNum

# start load balance nodes
start_lb_nodes 100000 1024

unset HostName
unset ECHO
unset CtlNode_ProcessNum
unset CtlNode_PortNum
unset ConnNode_ProcessNum
unset ConnNode_PortNum
unset PushNode_ProcessNum
unset PushNode_PortNum

