#!/bin/sh
#########################################################################################################

#check ebin directory
if [ ! -d ebin ]; then
	echo "ERROR: beam directory is not!"
	exit 1
fi

#import functions
. ./functions

#cd beam directory
cd ebin

ECHO="echo -e"

# start control and backup control nodes, see "./functions"
start_ctl_nodes 4194304 2048

#start mobile connection nodes, see "./functions"
start_conn_nodes 1572864 1048576

#start server push nodes, see "./functions"
start_push_nodes 4096 2048

